server:
  port: 7003

# virtual host name used by eureka server
spring.application.name: recommendation

eureka-server: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

spring.jpa.hibernate.ddl-auto: update

spring.datasource:
  url: jdbc:mysql://localhost/recom-db
  username: user
  password: pwd

spring.cloud.function.definition: messageProcessor

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings.messageProcessor-in-0:
    destination: recommendations

---
spring.config.activate.on-profile: docker
server.port: 8080

eureka-server: eureka

spring.datasource.url: jdbc:mysql://mysql/recom-db

spring.rabbitmq.host: rabbitmq

spring.cloud.stream.kafka.binder.brokers: kafka

---
spring.config.activate.on-profile: kafka

spring.cloud.stream.defaultBinder: kafka
spring.kafka.bootstrap-servers: kafka:9092
#spring.cloud.stream.kafka.binder.replication-factor: 1