version: '2.1'

services:
  product:
    build: microservices/product-service
    container_name: product
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker,kafka
    depends_on:
      mongodb:
        condition: service_healthy
      kafka:
        condition: service_started

  recommendation:
    build: microservices/product-recommendation
    container_name: recommendation
    mem_limit: 512m
    #ports:
    #  - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker,kafka
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started

  product-composite:
    build: microservices/product-composite
    container_name: composite
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker,kafka
    depends_on:
      kafka:
        condition: service_started

  mongodb:
    image: mongo:4.4.2
    container_name: mongodb
    mem_limit: 512m
    ports:
      - "27017:27017"
    command: mongod
    healthcheck:
      test: "mongo --eval 'db.stats().ok'"
      interval: 5s
      timeout: 2s
      retries: 60

  mysql:
    image: mysql:5.7.32
    container_name: mysql
    mem_limit: 512m
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=recom-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=pwd --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 60

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    mem_limit: 512m
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    mem_limit: 512m
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper
      
  eureka:
    build: springcloud/eureka
    container_name: eureka
    mem_limit: 512m

  gateway:
    build: springcloud/gateway
    container_name: gateway
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8080:8080
