server.port: 7000

SCHEME: http
PROD_SERVICE_HOST: localhost
PROD_SERVICE_PORT: 7001
PROD_RECOMMENDATION_HOST: localhost
PROD_RECOMMENDATION_PORT: 7003

# virtual host name used by eureka server
spring.application.name: composite

eureka-username: u
eureka-password: p

eureka-server: localhost
auth-server: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka-username}:${eureka-password}${eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings:
    products-out-0:
      destination: products
      producer:
        required-groups: auditGroup
    recommendations-out-0:
      destination: recommendations
      producer:
        required-groups: auditGroup

spring.security.oauth2.resourceserver.jwt.issuer-uri: http://${auth-server}:9999

---
spring.config.activate.on-profile: docker
server.port: 8080

SCHEME: http
PROD_SERVICE_HOST: product
PROD_SERVICE_PORT: 8080
PROD_RECOMMENDATION_HOST: recommendation
PROD_RECOMMENDATION_PORT: 8080

eureka-server: eureka
auth-server: authorization

spring.rabbitmq.host: rabbitmq

spring.cloud.stream.kafka.binder.brokers: kafka
